resolver: lts-12.6

ghc-options:
  $locals:
    -O2
    -Wall
    -Wno-name-shadowing
    -fmax-worker-args=1000
    -fsimpl-tick-factor=400
    -fspec-constr-keen
    -fspecialise-aggressively
    -fstatic-argument-transformation
    -funbox-strict-fields
    -threaded
  $everything:
    -fconstraint-solver-iterations=100

extra-deps:
    - git: 'git@github.com:luna/convert.git'
      commit: 69f5ff18fe453688ab0c932bb91f358e7622dde7
    - git: 'git@github.com:luna/functor-utils.git'
      commit: 822d083c67186d56c68a18a4558849590b81e994
    - git: 'git@github.com:luna/impossible.git'
      commit: 4615ea074b8b5d0ba7c45fd7056de349b8257d5b
    - git: 'git@github.com:luna/lens-utils.git'
      commit: 24f7ee7fa05379f4c507c6db272ec21049ae46ea
    - git: 'git@github.com:luna/monad-branch.git'
      commit: 054522f4bfcd9abebf0ddd87f33058738f0c660c
    - git: 'git@github.com:luna/monoid.git'
      commit: 11b010e27a56c46cbc1a7ac089642eac9e468af8
    - git: 'git@github.com:luna/prologue.git'
      commit: f13d39a758a0596ea7753051e430a11c53e10caa
    - git: 'git@github.com:luna/typelevel.git'
      commit: db4e4f883ae426d3ae8696cab3c932e58e0f4e9b
    - git: 'git@github.com:luna/container.git'
      commit: ca15fc1fdc19e6dac6e60d6a06773b75bb2a6fd5
    - git: 'git@github.com:luna/nested-containers.git'
      commit: 8b37f1fbcb7e4cada7b8e28e0778f73c7b69f0a8
    - git: 'git@github.com:luna/layered-state.git'
      commit: c970881b116464811ad4e222167ad65d361f8087
    - git: 'git@github.com:luna/luna.git'
      commit: 1f5f7194f371ea17df3c2f56f1c85a8eb6f3a320
      subdirs:
          - lib/data-typemap
          - lib/th-builder
          - lib/tuple-utils
          - lib/typelevel

